# Generated by Django 6.0.6 on 2026-06-27 07:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Result', 'Result'), ('Placement', 'Placement'), ('Event', 'Event')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['type'], name='notificatio_type_ea918f_idx'), models.Index(fields=['timestamp'], name='notificatio_timesta_ccadc8_idx')],
            },
        ),
    ]
