# Generated by Django 6.0.6 on 2026-06-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Result', 'Result'), ('Placement', 'Placement'), ('Event', 'Event'), ('Academic', 'Academic')], max_length=20),
        ),
    ]
